// Copyright 2014, Jens Hoffmann
//
// Euler problem 2 - Even Fibonacci numbers
//
// Each new term in the Fibonacci sequence is generated by
// adding the previous two terms. By starting with 1 and 2,
// the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose
// values do not exceed four million, find the sum of the
// even-valued terms.

public class euler002 {
    public static void main(String[] args) {
        int f0 = 1;
        int f1 = 2;
        int f2 = 3;
        int sum = 2;
        while (f2 < 4*1000*1000) {
            if (f2 % 2 == 0) {
                sum += f2;
            }
            f0 = f1;
            f1 = f2;
            f2 = f0 + f1;
        }
        System.out.println(sum);
    }
}
