// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Problem 2 - Even Fibonacci numbers
//
// Each new term in the Fibonacci sequence is generated by
// adding the previous two terms. By starting with 1 and 2,
// the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose
// values do not exceed four million, find the sum of the
// even-valued terms.
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <map>


void printUsage(char* progname) {
    printf("Usage: %s [-h] [-m <dynamic|naive>] <number>\n", progname);
}


std::map<int, int> fib_cache;


int fib_naive(int n) {
    if (n == 0)
        return 0;
    if (n == 1)
        return 1;
    return fib_naive(n - 2) + fib_naive(n - 1);
}


int fib_dynamic(int n) {
    if (fib_cache.count(n) == 0)
        fib_cache[n] = fib_dynamic(n - 2) + fib_dynamic(n - 1);
    return fib_cache[n];
}


int main(int argc, char** argv) {
    int result = 0;
    int number;
    char *fibFunType = NULL;
    int (*fibFunPtr)(int) = &fib_dynamic;
    int fib_i;
    int c;
    int i;

    opterr = 0;
    while ((c = getopt(argc, argv, "m:h")) != -1)
        switch (c) {
            case 'm':
                fibFunType = optarg;
                if (strcmp(fibFunType, "dynamic") == 0)
                    fibFunPtr = &fib_dynamic;
                else if (strcmp(fibFunType, "naive") == 0)
                    fibFunPtr = &fib_naive;
                else {
                    printf("No such fibonacci function implemented: fib_%s\n", fibFunType);
                    printUsage(argv[0]);
                    exit(1);
                }
                break;
            case 'h':
                printUsage(argv[0]);
                exit(0);
            default:
                abort();
        }
    
    if (optind >= argc) {
        printUsage(argv[0]);
        exit(0);
    }

    number = atoi(argv[optind]);

    fib_cache[0] = 0;
    fib_cache[1] = 1;

    i = 3;
    while (1) {
        fib_i = (*fibFunPtr)(i);
        if (fib_i > number)
            break;
        result += fib_i;
        i += 3;
    }

    printf(
        "The sum of all even fibonacci numbers that do not exceed %d is: %d\n",
        number, result
    );
}
